In [9]:
import logging
import os
os.getcwd()
os.chdir('C://Users//prata//Desktop//')
os.getcwd()

'C:\\Users\\prata\\Desktop'

In [36]:
logging.basicConfig(level=logging.ERROR)
logging.info("HI this is info")
logging.warning("HI this is warning")
logging.debug("HI this is debug")
logging.error("HI this is error")


ERROR:root:HI this is error


In [37]:
fruits = ['apple', 'mango', 'kiwi', 'watermelon', 'peer']
fruits

['apple', 'mango', 'kiwi', 'watermelon', 'peer']

In [43]:
l1 = [len(i) for i in fruits]
l2 = ['m', 'w']
l1

[5, 5, 4, 10, 4]

In [66]:
l2 = [j for j in fruits if j.startswith(('m', 'w'))]
l2

['mango', 'watermelon']

In [67]:
%save -r fname 1-50

The following commands were written to file `fname.ipy`:
import logging
logging.info("HI this is info")
logging.info("HI this is info")
logging.warning("HI this is warning")
logging.debug("HI this is debug")
logging.error("HI this is error")
logging.critical("HI this is critical")
logging.basicConfig('logging.txt', level='DEBUG')
logging.info("HI this is info")
logging.warning("HI this is warning")
logging.debug("HI this is debug")
logging.error("HI this is error")
logging.critical("HI this is critical")
logging.basicConfig(filename='logging.txt', level='DEBUG')
logging.info("HI this is info")
logging.warning("HI this is warning")
logging.debug("HI this is debug")
logging.error("HI this is error")
logging.critical("HI this is critical")
import logging
import os
os.getcwd()
import logging
import os
os.getcwd()
os.chdir('C:/Users/prata/Desktop/)
os.getcwd()
import logging
import os
os.getcwd()
os.chdir('C://Users//prata//Desktop//)
os.getcwd()
import logging
import os
os.getcwd()
os.chdi

writing magic methods below

<html><body><h1> HI this is HTML page </h1></body></html>

## head

##### head

* head

<em> text </em>

_head

<ul>
    <li>aaaaaaaaaa
    <li>bbbbbbbbbb
    <li>cccccccccc
</ul>

<a herf="https://www.google.com">Open google page</a>

In [81]:
%hist

import logging
logging.info("HI this is info")
logging.info("HI this is info")
logging.warning("HI this is warning")
logging.debug("HI this is debug")
logging.error("HI this is error")
logging.critical("HI this is critical")
logging.basicConfig('logging.txt', level='DEBUG')
logging.info("HI this is info")
logging.warning("HI this is warning")
logging.debug("HI this is debug")
logging.error("HI this is error")
logging.critical("HI this is critical")
logging.basicConfig(filename='logging.txt', level='DEBUG')
logging.info("HI this is info")
logging.warning("HI this is warning")
logging.debug("HI this is debug")
logging.error("HI this is error")
logging.critical("HI this is critical")
import logging
import os
os.getcwd()
import logging
import os
os.getcwd()
os.chdir('C:/Users/prata/Desktop/)
os.getcwd()
import logging
import os
os.getcwd()
os.chdir('C://Users//prata//Desktop//)
os.getcwd()
import logging
import os
os.getcwd()
os.chdir('C://Users//prata//Desktop//')
os.getcwd()
logging.basi

In [82]:
%history

import logging
logging.info("HI this is info")
logging.info("HI this is info")
logging.warning("HI this is warning")
logging.debug("HI this is debug")
logging.error("HI this is error")
logging.critical("HI this is critical")
logging.basicConfig('logging.txt', level='DEBUG')
logging.info("HI this is info")
logging.warning("HI this is warning")
logging.debug("HI this is debug")
logging.error("HI this is error")
logging.critical("HI this is critical")
logging.basicConfig(filename='logging.txt', level='DEBUG')
logging.info("HI this is info")
logging.warning("HI this is warning")
logging.debug("HI this is debug")
logging.error("HI this is error")
logging.critical("HI this is critical")
import logging
import os
os.getcwd()
import logging
import os
os.getcwd()
os.chdir('C:/Users/prata/Desktop/)
os.getcwd()
import logging
import os
os.getcwd()
os.chdir('C://Users//prata//Desktop//)
os.getcwd()
import logging
import os
os.getcwd()
os.chdir('C://Users//prata//Desktop//')
os.getcwd()
logging.basi

*python*

-python-

**python**

In [84]:
_i1

'import logging'

In [85]:
_i2

'logging.info("HI this is info")'

In [114]:
import numpy as np
a1 = np.array([3, 4, 5, 3, 2, 1])
print(a1)

[3 4 5 3 2 1]


In [107]:
a1.dtype

dtype('S2')

In [104]:
type(a1)

numpy.ndarray

In [120]:
a2 = np.array([5, 4, 6, 2], ndmin=2)
a2

array([[5, 4, 6, 2]])

In [127]:
a3 = np.array((((3, 5, 3, 8))))
np.ndim(a3)

1

In [130]:
a4 = np.array([[[3, 4, 5]]])
print(a4)
print(np.ndim(a4))

[[[3 4 5]]]
3


In [143]:
a5 = np.array([5, 3, 4, 7, 8, 1, 3])
for i, j in np.ndenumerate(a5):
    print(i, end='')
    print(j)

(0,)5
(1,)3
(2,)4
(3,)7
(4,)8
(5,)1
(6,)3


In [162]:
lst2 = np.array([[-1, 4, 3, 5], [4, 6, -3, 9]])
def arrlst(*lst):
    lst1 = np.array(lst2)
    print('lst1', lst1)
    print('data type', lst1.dtype)
    print('dimention of array ', np.ndim(lst1))
    print('shape of array', lst1.shape)
    print('size of array', np.size(lst1))
    print('each element size', lst1.itemsize)
    
arrlst(lst)

lst1 [[-1  4  3  5]
 [ 4  6 -3  9]]
data type int32
dimention of array  2
shape of array (2, 4)
size of array 8
each element size 4


In [167]:
from numpy import random
a5 = np.array([4, 3, 6, 2, 6, 3, 9, 8, 1, 4, 2, 4])
x = random.choice(a5, size = (3, 5))
print(x)


[[2 2 2 4 6]
 [9 6 3 9 2]
 [2 6 4 3 8]]


In [169]:
np.zeros(shape = (3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [172]:
np.full(shape = (3, 4), fill_value = 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [176]:
np.ones(shape = (3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [180]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [205]:
np.linspace(30, 100, 10, 9)

array([ 30.        ,  37.77777778,  45.55555556,  53.33333333,
        61.11111111,  68.88888889,  76.66666667,  84.44444444,
        92.22222222, 100.        ])

In [199]:
70/9

7.777777777777778

In [222]:
np.random.randint(4, 80, 2)

array([76, 27])

In [225]:
np.random.choice([2, 3, 4], size = (3, 3, 6))

array([[[2, 4, 2, 3, 4, 2],
        [4, 4, 4, 2, 3, 3],
        [3, 4, 3, 4, 2, 3]],

       [[4, 3, 3, 4, 2, 3],
        [4, 4, 2, 4, 4, 2],
        [4, 4, 4, 4, 2, 3]],

       [[2, 4, 2, 2, 3, 3],
        [3, 3, 4, 3, 4, 3],
        [3, 3, 4, 2, 2, 3]]])

In [227]:
print(np.array(([1, 2,], (3, 4))).ndim)

2


In [285]:
x2 = np.zeros(shape = (4, 4))
print(x2)
x22 = np.random.rand(5, 5)
x22

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


array([[0.31209973, 0.48324792, 0.98101388, 0.77546109, 0.63310068],
       [0.49040258, 0.70312935, 0.2429623 , 0.70234896, 0.08300544],
       [0.08882619, 0.67931538, 0.54937961, 0.41451082, 0.86383705],
       [0.5299501 , 0.09542635, 0.39836866, 0.96990637, 0.53294471],
       [0.07036487, 0.97787025, 0.61231664, 0.62772579, 0.23258295]])

In [278]:
x3 = np.ones(shape = (3, 2, 3))
x3
r1 = np.ravel(x3)
for i in r1:
    if i%2 == 0:
        r1[0, 1, i] = 0
print(r1)
# np.rot90(r1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [263]:
x22[np.diag_indices_from(x22)] = 1
x22

array([[1.        , 0.20998188, 0.25613656, 0.35645927, 0.58678584],
       [0.21827272, 1.        , 0.90235167, 0.25860405, 0.86321314],
       [0.23640708, 0.41085981, 1.        , 0.51831467, 0.00814079],
       [0.24048681, 0.43022531, 0.68105366, 1.        , 0.85737833],
       [0.5459549 , 0.61787386, 0.73345387, 0.86380151, 1.        ]])

In [280]:
for c, d in np.ndenumerate(x2):
    print(c)
    print(d)

(0, 0, 0)
0.0
(0, 0, 1)
0.0
(0, 0, 2)
0.0
(0, 1, 0)
0.0
(0, 1, 1)
0.0
(0, 1, 2)
0.0
(1, 0, 0)
0.0
(1, 0, 1)
0.0
(1, 0, 2)
0.0
(1, 1, 0)
0.0
(1, 1, 1)
0.0
(1, 1, 2)
0.0
(2, 0, 0)
0.0
(2, 0, 1)
0.0
(2, 0, 2)
0.0
(2, 1, 0)
0.0
(2, 1, 1)
0.0
(2, 1, 2)
0.0


In [331]:
o1 = np.ones(shape = (4,4))
print(o1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [334]:
for e, f in np.ndenumerate(o1):
    e1, e2 = e
    if e1 == e2 or e1+e2 == 3:
        continue
    else:
        o1[e1,e2] = 0
print(o1)

[[1. 0. 0. 1.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [1. 0. 0. 1.]]


In [339]:
r2 = np.arange(1, 22)
print(np.where(r2%2 != 0))

(array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20], dtype=int64),)


In [340]:
l4 = np.linspace(10, 20, 30)
print(l4)

[10.         10.34482759 10.68965517 11.03448276 11.37931034 11.72413793
 12.06896552 12.4137931  12.75862069 13.10344828 13.44827586 13.79310345
 14.13793103 14.48275862 14.82758621 15.17241379 15.51724138 15.86206897
 16.20689655 16.55172414 16.89655172 17.24137931 17.5862069  17.93103448
 18.27586207 18.62068966 18.96551724 19.31034483 19.65517241 20.        ]


In [341]:
r4 = np.random.rand(5, 5)
r4

array([[0.43114869, 0.38420798, 0.25848146, 0.31186141, 0.15527627],
       [0.21257636, 0.84539932, 0.79848018, 0.39628156, 0.40585133],
       [0.45427379, 0.46203178, 0.19118363, 0.20265242, 0.25079046],
       [0.59742613, 0.82151232, 0.9166843 , 0.77183899, 0.82558511],
       [0.41189466, 0.08250145, 0.16934864, 0.87432489, 0.81386235]])

In [356]:
np.hstack(l4)

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])